### ISSUE TITLE
Merge build scripts

### ISSUE THREAD

**Issue by j-simmons-phd** [Mach30/m30ml#2]
I made a local build script and we need to merge it with build.sh and set it up so we can run in docker or not with a switch (not should be default, and the CI pipeline should be updated to call with docker enabled).

**Comment by j-simmons-phd** [comment]
See https://github.com/mikefarah/yq#run-with-docker-or-podman

**Comment by capsulecorplab** [comment]
slightly better docker command https://github.com/mikefarah/yq#oneshot-use

**Comment by capsulecorplab** [comment]
can follow same pattern as https://github.com/capsulecorplab/docs-as-code/blob/main/build.sh
